Feature/cdpt 1661 404 updates
ministryofjustice/justice-gov-uk pull request #177
Opened 2024-05-24 15:27 UTC by EmilyHazlehurst

2024-05-24 15:54 UTC, EarthlingDavey reviewed
Looks good! If we're removing GTM from the maintenance page, should we also remove it from the other error pages?

2024-05-29 16:51 UTC, EarthlingDavey approved these changes
Looks good ! 😊

2024-05-30 12:17 UTC, wilson1000 requested changes
Hi @EmilyHazlehurst - great stuff
I've made some comments regarding how we prepare images for distribution.

Also, can we please put the GTM code back with the correct GTM ID? This code allow us to create error reports and track error pages in Google Analytics.

2024-05-30 12:17 UTC, wilson1000 commented on public/app/themes/justice/error-pages/maintenance.html
> +        <img src="/app/themes/justice/src/img/crown_copyright_logo.png" alt="crown copyright logo">
Hi @EmilyHazlehurst the stacks will need to reference `dist` - `src` doesn't exist in the file system.

2024-05-30 12:17 UTC, wilson1000 commented on public/app/themes/justice/error-pages/maintenance.html
> +      <img src="/app/themes/justice/src/img/moj-logo.gif" alt="MoJ Logo">
Can we reference `dist`?

**The process is...**
LaravelMix should process the image from `src`, apply compressions if necessary and place the image in the `dist` directory structure for use in production. `src` isn't there 👍 

![Screenshot 2024-05-30 at 13 11 28](https://github.com/ministryofjustice/justice-gov-uk/assets/1674630/d8814206-2889-4c7d-8b27-a1389ac5272b)

2024-05-30 12:17 UTC, wilson1000 commented on public/app/themes/justice/error-pages/maintenance.html
> +  <link rel="stylesheet" href="/app/themes/justice/src/css/global.css"/>
`src -> dist` mentioned below 😄

2024-05-30 12:28 UTC, wilson1000 commented
We set up error pages in our `server.conf` configuration. Some rules allow access to certain directories when server access is restricted.

Interestingly, 401 isn't in there, but 400 is. 
What should we do about this?

```php
    error_page 400 /app/themes/justice/error-pages/400.html;
    error_page 404 /app/themes/justice/error-pages/404.html;
    error_page 500 /app/themes/justice/error-pages/500.html;
    error_page 503 /app/themes/justice/error-pages/maintenance.html;

    # Empty location blocks to allow access when "/" location
    # sends an HTTP 503 during maintenance mode
    location /app/themes/justice/error-pages/ { }
    location /app/themes/justice/dist/ { }
```

2024-06-11 08:21 UTC, wilson1000 commented
Good morning @EmilyHazlehurst 👋 

For error pages, I've created a file in `dist/patch/js/ccfw-check-consent.js` that can be used to drop the GTM code. We need to make sure that the GTM ID is available on the page, in a `data-allowed` attribute I think 🤔  - please do check this if you choose to use the file, I hope it's helpful.

https://github.com/ministryofjustice/justice-gov-uk/blob/main/public/app/themes/justice/src/patch/js/ccfw-check-consent.js

2024-06-11 10:23 UTC, EmilyHazlehurst commented
> Good morning @EmilyHazlehurst 👋
> 
> For error pages, I've created a file in `dist/patch/js/ccfw-check-consent.js` that can be used to drop the GTM code. We need to make sure that the GTM ID is available on the page, in a `data-allowed` attribute I think 🤔 - please do check this if you choose to use the file, I hope it's helpful.
> 
> https://github.com/ministryofjustice/justice-gov-uk/blob/main/public/app/themes/justice/src/patch/js/ccfw-check-consent.js

Thanks @wilson1000. I think for now it's probably best to keep this as it is as the goal of the ticket was just to change the title and and search link on the pages. I've added the original gtm code back in and have updated the ID.

Perhaps we can improve this further as part of the frontend work, since the error pages have some accessibility issues and are quite messy? I can make a ticket for it today.

2024-06-11 19:41 UTC, wilson1000 approved these changes
Thanks Emily 😄

2024-06-11 19:49 UTC, merged